kind: pipeline
name: latest
## Push to Docker
steps:
- name: docker
  image: plugins/docker
  settings:
    repo: ikifar/visual-studio-codespace-docker
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password